### PR TITLE
Apply fixes to support Amazon Echo Dot (3rd Generation)

### PR DESCRIPTION
**Pull request by datech**
Fixes are tested with Amazon Echo Dot (3rd Generation) and Node-RED v0.19.5

### CODE REVIEW

**Comment by Keltere** [comment]
Hi, sorry but i get this error
ReferenceError: port is not defined and neither my dot 3 neither my echo gen 2 seem to find the device. Are you sure it's a working fix?

**Comment by Knacki** [comment]
There is a bug in the code. 
Edit the line "port = 80;" to "var port =80;" 
and comment back in the "var lightId = formatUUID(config.id);" line
or you get an another error :)

**Comment by Keltere** [comment]
@Knacki thanks, it's working now

**Comment by Knacki** [comment]
but you would have a other problem, you can only discover one device :( because the Port is fix to port 80.

**Comment by torinnguyen** [comment]
This fix will allow only 1 alexa-local node to be deployed. Am I right?

**Comment by Keltere** [comment]
Tested, yes just 1.

**Comment by Knacki** [comment]
yes... :(

**Pull request merged**
